version: "3.8"

services:
  app:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: uvicorn app.main:app --host ${API_HOST} --port ${API_PORT} --reload

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
