apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remindarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/krishnarajt/remindarr
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: remindarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
